/**
 * Enteral Nutrition Products Database
 * Structured according to the new schema
 */

const ENTERAL_PRODUCTS = Object.freeze([
  {
    name: "PentaSure DM",
    category: "Diabetes",
    manufacturer: "Pentasure",
    isActive: true,
    displayOrder: 1,
    standardDilution: {
      scoops: 4,
      scoopsText: "level scoops",
      powderGrams: 50,
      waterMl: 200,
      finalVolumeMl: 237,
      calories: 229,
      protein: 11.3,
      fat: 9.35,
      carbohydrate: 25,
      sodium: 150,
      potassium: 225,
      phosphorus: 162.5,
      preparationInstruction: "4 level scoops (50g) in 200ml water",
    },
  },
  {
    name: "PentaSure HP",
    category: "High Protein",
    manufacturer: "Pentasure",
    isActive: true,
    displayOrder: 2,
    standardDilution: {
      scoops: 2,
      scoopsText: "level scoops",
      powderGrams: 30,
      waterMl: 120,
      finalVolumeMl: 144,
      calories: 116,
      protein: 13.5,
      fat: 1.04,
      carbohydrate: 13.2,
      sodium: 180,
      potassium: 240,
      phosphorus: 171,
      preparationInstruction: "2 level scoops (30g) in 120ml water",
    },
  },
  {
    name: "PentaSure 2.0",
    category: "High Calorie, High Protein",
    manufacturer: "Pentasure",
    isActive: true,
    displayOrder: 3,
    standardDilution: {
      scoops: 4,
      scoopsText: "level scoops",
      powderGrams: 54,
      waterMl: 65,
      finalVolumeMl: 108,
      calories: 243,
      protein: 18.74,
      fat: 8.64,
      carbohydrate: 23.22,
      sodium: 67.83,
      potassium: 113.4,
      phosphorus: 81,
      preparationInstruction: "4 level scoops (54g) in 65 ml water",
    },
  },
  {
    name: "PentaSure Renal",
    category: "Low protein",
    manufacturer: "Pentasure",
    isActive: true,
    displayOrder: 4,
    standardDilution: {
      scoops: 4,
      scoopsText: "heaped scoops",
      powderGrams: 42,
      waterMl: 66,
      finalVolumeMl: 100,
      calories: 199.05,
      protein: 5.46,
      fat: 9.24,
      carbohydrate: 23.52,
      sodium: 42,
      potassium: 50.4,
      phosphorus: 63,
      preparationInstruction: "4 heaped scoops (42g) in 66ml water",
    },
  },
  {
    name: "PentaSure Hepatic",
    category: "Heaptic",
    manufacturer: "Pentasure",
    isActive: true,
    displayOrder: 5,
    standardDilution: {
      scoops: 4,
      scoopsText: "heaped scoops",
      powderGrams: 50,
      waterMl: 100,
      finalVolumeMl: 138,
      calories: 207,
      protein: 8.75,
      fat: 4.5,
      carbohydrate: 32.5,
      sodium: 120,
      potassium: 180,
      phosphorus: 100,
      preparationInstruction: "4 heaped scoops (50g) in 100ml water",
    },
  },
  {
    name: "PentaSure CRITIPEP",
    category: "Peptide diet",
    manufacturer: "Pentasure",
    isActive: true,
    displayOrder: 6,
    standardDilution: {
      scoops: 2,
      scoopsText: "heaped scoops",
      powderGrams: 20,
      waterMl: 85,
      finalVolumeMl: 102,
      calories: 99,
      protein: 4,
      fat: 4.5,
      carbohydrate: 10.5,
      sodium: 30,
      potassium: 128,
      phosphorus: 70,
      preparationInstruction: "2 heaped scoops (20g) in 85ml water",
    },
  },
  {
    name: "PentaSure DLS",
    category: "Dialysis",
    manufacturer: "Pentasure",
    isActive: true,
    displayOrder: 7,
    standardDilution: {
      scoops: 4,
      scoopsText: "heaped scoops",
      powderGrams: 42,
      waterMl: 66,
      finalVolumeMl: 100,
      calories: 206.65,
      protein: 10.5,
      fat: 10.4,
      carbohydrate: 17.75,
      sodium: 58.8,
      potassium: 98.5,
      phosphorus: 59.5,
      preparationInstruction: "4 heaped scoops (42g) in 66ml water",
    },
  },
  {
    name: "Pedia Gold",
    category: "Pediatrics",
    manufacturer: "Pentasure",
    isActive: true,
    displayOrder: 8,
    standardDilution: {
      scoops: 2,
      scoopsText: "heaped scoops",
      powderGrams: 40,
      waterMl: 160,
      finalVolumeMl: 190,
      calories: 190,
      protein: 6,
      fat: 7.4,
      carbohydrate: 24.9,
      sodium: 60.8,
      potassium: 160,
      phosphorus: 58,
      preparationInstruction: "2 heaped scoops (40g) in 160 ml water",
    },
  },
  {
    name: "Pedia Gold Plus",
    category: "Pediatric peptide diet",
    manufacturer: "Pentasure",
    isActive: true,
    displayOrder: 9,
    standardDilution: {
      scoops: 2,
      scoopsText: "heaped scoops",
      powderGrams: 40,
      waterMl: 160,
      finalVolumeMl: 190,
      calories: 190,
      protein: 5.7,
      fat: 7.4,
      carbohydrate: 25.2,
      sodium: 58.8,
      potassium: 160,
      phosphorus: 60,
      preparationInstruction: "2 heaped scoops (40g) in 160 ml water",
    },
  },
  {
    name: "KABIPRO",
    category: "KABIPRO",
    manufacturer: "Fresenius Kabi",
    isActive: true,
    displayOrder: 10,
    standardDilution: {
      scoops: 2,
      scoopsText: "leveled scoops",
      powderGrams: 24,
      waterMl: 200,
      finalVolumeMl: 220,
      calories: 87.6,
      protein: 10.08,
      fat: 0.72,
      carbohydrate: 10.8,
      sodium: 55.2,
      potassium: 164.4,
      phosphorus: 93.6,
      preparationInstruction: "2 leveled scoops (24g) in 200ml water",
    },
  },
  {
    name: "FRESUBIN DM",
    category: "Diabetes",
    manufacturer: "Fresenius Kabi",
    isActive: true,
    displayOrder: 11,
    standardDilution: {
      scoops: 4,
      scoopsText: "leveled scoops",
      powderGrams: 50,
      waterMl: 170,
      finalVolumeMl: 218,
      calories: 223,
      protein: 10.1,
      fat: 10,
      carbohydrate: 24.9,
      sodium: 180,
      potassium: 299.5,
      phosphorus: 150,
      preparationInstruction: "4 leveled scoops (50g) in 170ml water",
    },
  },
  {
    name: "FRESUBIN HP",
    category: "High Protein",
    manufacturer: "Fresenius Kabi",
    isActive: true,
    displayOrder: 12,
    standardDilution: {
      scoops: 3,
      scoopsText: "leveled scoops",
      powderGrams: 42,
      waterMl: 60,
      finalVolumeMl: 100,
      calories: 200.34,
      protein: 9.03,
      fat: 10.5,
      carbohydrate: 18.48,
      sodium: 63.38,
      potassium: 98.7,
      phosphorus: 63.38,
      preparationInstruction: "3 leveled scoops (42g) in 60ml water",
    },
  },
  {
    name: "ENSURE DM",
    category: "Diabetes",
    manufacturer: "Abott",
    isActive: true,
    displayOrder: 13,
    standardDilution: {
      scoops: 5,
      scoopsText: "leveled scoops",
      powderGrams: 52.1,
      waterMl: 200,
      finalVolumeMl: 237,
      calories: 217.25,
      protein: 10.8,
      fat: 8.7,
      carbohydrate: 22.02,
      sodium: 211,
      potassium: 369.91,
      phosphorus: 168.2,
      preparationInstruction: "5 leveled scoops (52.1g) in 200ml water",
    },
  },
  {
    name: "ENSURE PLUS",
    category: "Standard",
    manufacturer: "Abott",
    isActive: true,
    displayOrder: 14,
    standardDilution: {
      scoops: 6,
      scoopsText: "leveled scoops",
      powderGrams: 55,
      waterMl: 190,
      finalVolumeMl: 231,
      calories: 238.7,
      protein: 10.45,
      fat: 6.54,
      carbohydrate: 33.04,
      sodium: 150.15,
      potassium: 314.05,
      phosphorus: 121.55,
      preparationInstruction: "6 leveled scoops (55g) in 190ml water",
    },
  },
  {
    name: "HINEX ST",
    category: "Standard",
    manufacturer: "Otsuka",
    isActive: true,
    displayOrder: 15,
    standardDilution: {
      scoops: 4,
      scoopsText: "leveled scoops",
      powderGrams: 50,
      waterMl: 185,
      finalVolumeMl: 200,
      calories: 224,
      protein: 9.5,
      fat: 8,
      carbohydrate: 29.4,
      sodium: 155,
      potassium: 254,
      phosphorus: 127,
      preparationInstruction: "4 leveled scoops (50g) in 185ml water",
    },
  },
  {
    name: "HINEX ST PLUS",
    category: "Probiotic",
    manufacturer: "Otsuka",
    isActive: true,
    displayOrder: 16,
    standardDilution: {
      scoops: 4,
      scoopsText: "leveled scoops",
      powderGrams: 50,
      waterMl: 180,
      finalVolumeMl: 200,
      calories: 220,
      protein: 11,
      fat: 7.5,
      carbohydrate: 28.3,
      sodium: 162,
      potassium: 267,
      phosphorus: 125,
      preparationInstruction: "4 leveled scoops (50g) in 180ml water",
    },
  },
  {
    name: "HINEX DM",
    category: "Diabetic",
    manufacturer: "Otsuka",
    isActive: true,
    displayOrder: 17,
    standardDilution: {
      scoops: 4,
      scoopsText: "leveled scoops",
      powderGrams: 50,
      waterMl: 190,
      finalVolumeMl: 200,
      calories: 228,
      protein: 11.4,
      fat: 10.1,
      carbohydrate: 25.3,
      sodium: 152,
      potassium: 266,
      phosphorus: 135,
      preparationInstruction: "4 leveled scoops (50g) in 190ml water",
    },
  },
  {
    name: "HINEX HP",
    category: "High Protein",
    manufacturer: "Otsuka",
    isActive: true,
    displayOrder: 18,
    standardDilution: {
      scoops: 2,
      scoopsText: "leveled scoops",
      powderGrams: 25,
      waterMl: 150,
      finalVolumeMl: 200,
      calories: 89,
      protein: 11.3,
      fat: 0.28,
      carbohydrate: 11.4,
      sodium: 60,
      potassium: 190,
      phosphorus: 63,
      preparationInstruction: "2 leveled scoops (25g) in 150ml water",
    },
  },
  {
    name: "RESOURCE HP",
    category: "High Protein ",
    manufacturer: "Nestle-Dr Reddy",
    isActive: true,
    displayOrder: 19,
    standardDilution: {
      scoops: 6,
      scoopsText: "leveled scoops",
      powderGrams: 50,
      waterMl: 150,
      finalVolumeMl: 200,
      calories: 174,
      protein: 21,
      fat: 1,
      carbohydrate: 21.3,
      sodium: 105,
      potassium: 0,
      phosphorus: 215,
      preparationInstruction: "6 leveled scoops (50g) in 150ml water",
    },
  },
  {
    name: "RESOURCE OPTI",
    category: "Standard ",
    manufacturer: "Nestle-Dr Reddy",
    isActive: true,
    displayOrder: 20,
    standardDilution: {
      scoops: 6,
      scoopsText: "leveled scoops",
      powderGrams: 50,
      waterMl: 190,
      finalVolumeMl: 225,
      calories: 214.5,
      protein: 10,
      fat: 7.5,
      carbohydrate: 28,
      sodium: 113,
      potassium: 237,
      phosphorus: 150,
      preparationInstruction: "6 leveled scoops (50g) in 190ml water",
    },
  },
  {
    name: "RESOURCE Dialysis",
    category: "Dialysis ",
    manufacturer: "Nestle-Dr Reddy",
    isActive: true,
    displayOrder: 21,
    standardDilution: {
      scoops: 6,
      scoopsText: "leveled scoops",
      powderGrams: 50,
      waterMl: 90,
      finalVolumeMl: 139,
      calories: 217,
      protein: 13.5,
      fat: 8.15,
      carbohydrate: 23.65,
      sodium: 72.5,
      potassium: 172.5,
      phosphorus: 116,
      preparationInstruction: "6 leveled scoops (50g) in 90ml water",
    },
  },
  {
    name: "RESOURCE Renal",
    category: "Low Protein ",
    manufacturer: "Nestle-Dr Reddy",
    isActive: true,
    displayOrder: 22,
    standardDilution: {
      scoops: 6,
      scoopsText: "leveled scoops",
      powderGrams: 50,
      waterMl: 90,
      finalVolumeMl: 139,
      calories: 223.5,
      protein: 6,
      fat: 7.95,
      carbohydrate: 33.2,
      sodium: 71,
      potassium: 150,
      phosphorus: 71.5,
      preparationInstruction: "6 leveled scoops (50g) in 90ml water",
    },
  },
  {
    name: "RESOURCE Diabetic",
    category: "Diabetic ",
    manufacturer: "Nestle-Dr Reddy",
    isActive: true,
    displayOrder: 23,
    standardDilution: {
      scoops: 6,
      scoopsText: "leveled scoops",
      powderGrams: 50,
      waterMl: 190,
      finalVolumeMl: 231,
      calories: 213.5,
      protein: 12,
      fat: 7.95,
      carbohydrate: 25.05,
      sodium: 107.5,
      potassium: 274,
      phosphorus: 150,
      preparationInstruction: "6 leveled scoops (50g) in 190ml water",
    },
  },
  {
    name: "PEPTAMEN ADULT",
    category: "Peptide ",
    manufacturer: "Nestle-Dr Reddy",
    isActive: true,
    displayOrder: 24,
    standardDilution: {
      scoops: 7,
      scoopsText: "leveled scoops",
      powderGrams: 55,
      waterMl: 210,
      finalVolumeMl: 250,
      calories: 257.95,
      protein: 10.06,
      fat: 9.9,
      carbohydrate: 32.17,
      sodium: 203.5,
      potassium: 374,
      phosphorus: 139.7,
      preparationInstruction: "7 leveled scoops (55g) in 210ml water",
    },
  },
  {
    name: "PEPTAMEN JUNIOR",
    category: "Peptide ",
    manufacturer: "Nestle-Dr Reddy",
    isActive: true,
    displayOrder: 25,
    standardDilution: {
      scoops: 7,
      scoopsText: "leveled scoops",
      powderGrams: 55,
      waterMl: 210,
      finalVolumeMl: 250,
      calories: 254.65,
      protein: 7.09,
      fat: 9.07,
      carbohydrate: 36.19,
      sodium: 151.58,
      potassium: 298.1,
      phosphorus: 136.95,
      preparationInstruction: "7 leveled scoops (55g) in 210ml water",
    },
  },
  {
    name: "CELEVIDA EN - 1 Kcal/ml",
    category: "Standard ",
    manufacturer: "Nestle-Dr Reddy",
    isActive: true,
    displayOrder: 27,
    standardDilution: {
      scoops: 2,
      scoopsText: "leveled scoops",
      powderGrams: 50,
      waterMl: 200,
      finalVolumeMl: 230,
      calories: 220,
      protein: 10.5,
      fat: 8,
      carbohydrate: 26,
      sodium: 217.5,
      potassium: 136.5,
      phosphorus: 86.95,
      preparationInstruction: "2 leveled scoops (50g) in 200ml water",
    },
  },
  {
    name: "CELEVIDA EN - 1.52 Kcal/ml",
    category: "Standard ",
    manufacturer: "Nestle-Dr Reddy",
    isActive: true,
    displayOrder: 26,
    standardDilution: {
      scoops: 2,
      scoopsText: "leveled scoops",
      powderGrams: 50,
      waterMl: 125,
      finalVolumeMl: 150,
      calories: 220,
      protein: 10.5,
      fat: 8,
      carbohydrate: 26,
      sodium: 217.5,
      potassium: 136.5,
      phosphorus: 86.95,
      preparationInstruction: "2 leveled scoops (50g) in 125ml water",
    },
  },
  {
    name: "CELEVIDA EN - 1.69 Kcal/ml",
    category: "Standard ",
    manufacturer: "Nestle-Dr Reddy",
    isActive: true,
    displayOrder: 28,
    standardDilution: {
      scoops: 2,
      scoopsText: "leveled scoops",
      powderGrams: 50,
      waterMl: 110,
      finalVolumeMl: 135,
      calories: 220,
      protein: 10.5,
      fat: 8,
      carbohydrate: 26,
      sodium: 217.5,
      potassium: 136.5,
      phosphorus: 86.95,
      preparationInstruction: "2 leveled scoops (50g) in 110ml water",
    },
  },
  {
    name: "CELEVIDA EN - 2 Kcal/ml",
    category: "Standard ",
    manufacturer: "Nestle-Dr Reddy",
    isActive: true,
    displayOrder: 29,
    standardDilution: {
      scoops: 2,
      scoopsText: "leveled scoops",
      powderGrams: 50,
      waterMl: 90,
      finalVolumeMl: 110,
      calories: 220,
      protein: 10.5,
      fat: 8,
      carbohydrate: 26,
      sodium: 217.5,
      potassium: 136.5,
      phosphorus: 86.95,
      preparationInstruction: "2 leveled scoops (50g) in 90ml water",
    },
  },
]);

/**
 * Filter thresholds for product categorization
 */
const FILTER_THRESHOLDS = Object.freeze({
  LOW_SODIUM: 200, // mg per standard preparation
  FLUID_RESTRICTION: 2.0, // kcal/ml (calorie density, high energy dense)
  HIGH_PROTEIN: 15, // g per standard preparation
  LOW_PROTEIN: 12, // g per standard preparation
  LOW_CALORIE_DENSITY: 0.7, // kcal/ml — dilute formulas (≤0.7 kcal/ml)
  HIGH_CALORIE_DENSITY: 1.5, // kcal/ml — concentrated formulas (≥1.5 kcal/ml)
});
